// Generated by scripts/generate-icons.mjs; do not edit by hand.
import type { SVGProps } from "react";

export type IconProps = SVGProps<SVGSVGElement>;
export type IconComponent = (props: IconProps) => React.JSX.Element;

function createIcon(id: string): IconComponent {
  function SpriteIcon(props: IconProps) {
    return (
      <svg width="24" height="24" aria-hidden="true" {...props}>
        <use href={`/icons.svg#${id}`} />
      </svg>
    );
  }
  return SpriteIcon;
}

export const Activity = createIcon("activity");
export const AlertCircle = createIcon("alert-circle");
export const AlertTriangle = createIcon("alert-triangle");
export const Apple = createIcon("apple");
export const ArrowRight = createIcon("arrow-right");
export const ArrowUpRight = createIcon("arrow-up-right");
export const Baby = createIcon("baby");
export const BadgeCheck = createIcon("badge-check");
export const BookOpen = createIcon("book-open");
export const BookOpenCheck = createIcon("book-open-check");
export const Calculator = createIcon("calculator");
export const CalendarDays = createIcon("calendar-days");
export const CalendarHeart = createIcon("calendar-heart");
export const Check = createIcon("check");
export const CheckCircle2 = createIcon("check-circle-2");
export const ChevronDown = createIcon("chevron-down");
export const ChevronLeft = createIcon("chevron-left");
export const ChevronRight = createIcon("chevron-right");
export const ChevronUp = createIcon("chevron-up");
export const Clock = createIcon("clock");
export const Cookie = createIcon("cookie");
export const Database = createIcon("database");
export const Eraser = createIcon("eraser");
export const ExternalLink = createIcon("external-link");
export const FileText = createIcon("file-text");
export const HeartPulse = createIcon("heart-pulse");
export const Home = createIcon("home");
export const Info = createIcon("info");
export const LayoutGrid = createIcon("layout-grid");
export const Leaf = createIcon("leaf");
export const Loader2 = createIcon("loader-2");
export const Lock = createIcon("lock");
export const LockKeyhole = createIcon("lock-keyhole");
export const Mail = createIcon("mail");
export const Map = createIcon("map");
export const MessageCircle = createIcon("message-circle");
export const Newspaper = createIcon("newspaper");
export const Play = createIcon("play");
export const RefreshCw = createIcon("refresh-cw");
export const Scale = createIcon("scale");
export const Send = createIcon("send");
export const Server = createIcon("server");
export const ShieldCheck = createIcon("shield-check");
export const Sparkles = createIcon("sparkles");
export const Target = createIcon("target");
