// Builds public/icons.svg (one <symbol> per icon, from lucide-react) and
// app/components/icons.tsx (tiny components that reference the sprite), so
// pages ship a short <use> tag instead of full inline SVG paths.
// Icons are discovered from imports in app/; re-run after adding an icon.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import * as lucide from "lucide-react";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const appDir = path.join(root, "app");
const IMPORT = /import\s*(?:type\s*)?\{([^}]*)\}\s*from\s*"(lucide-react|(?:\.{1,2}\/)+(?:components\/)?icons)"/g;

function walk(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return walk(full);
    return /\.(tsx?|jsx?)$/.test(entry.name) ? [full] : [];
  });
}

const names = new Set();
for (const file of walk(appDir)) {
  if (file.endsWith(path.join("components", "icons.tsx"))) continue;
  for (const match of readFileSync(file, "utf8").matchAll(IMPORT)) {
    for (const part of match[1].split(",")) {
      const name = part.trim().replace(/^type\s+/, "").split(/\s+as\s+/)[0];
      if (name && !["LucideIcon", "IconComponent", "IconProps"].includes(name)) names.add(name);
    }
  }
}

const kebab = (name) =>
  name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Za-z])([0-9])/g, "$1-$2")
    .toLowerCase();

const sorted = [...names].sort();
const symbols = sorted.map((name) => {
  const component = lucide[name];
  if (!component) throw new Error(`Unknown lucide icon: ${name}`);
  const markup = renderToStaticMarkup(createElement(component));
  const inner = markup.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");
  return `<symbol id="${kebab(name)}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${inner}</symbol>`;
});

writeFileSync(
  path.join(root, "public", "icons.svg"),
  `<svg xmlns="http://www.w3.org/2000/svg">${symbols.join("")}</svg>\n`,
);

const components = sorted.map((name) => `export const ${name} = createIcon("${kebab(name)}");`).join("\n");

writeFileSync(
  path.join(appDir, "components", "icons.tsx"),
  `// Generated by scripts/generate-icons.mjs; do not edit by hand.
import type { SVGProps } from "react";

export type IconProps = SVGProps<SVGSVGElement>;
export type IconComponent = (props: IconProps) => React.JSX.Element;

function createIcon(id: string): IconComponent {
  function SpriteIcon(props: IconProps) {
    return (
      <svg width="24" height="24" aria-hidden="true" {...props}>
        <use href={\`/icons.svg#\${id}\`} />
      </svg>
    );
  }
  return SpriteIcon;
}

${components}
`,
);

console.log(`generate-icons: ${sorted.length} icons`);
